/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("at.meks.easyvalidation.java-conventions")
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    testImplementation("org.assertj:assertj-core:3.24.2")
    testImplementation("org.mockito:mockito-core:5.3.1")
}

description = "Easy Validation core"

java {
    withJavadocJar()
}
